### PR TITLE
Create single script for batch transfers, refactor Setup.py and Youtube.py

### PR DESCRIPTION
**Pull request by PattoMotto**
- Refactor Setup.py and Youtube.py so they can be called from another script.
- Create SpotifyToYoutube.py which requires `youtube_headers_raw.txt` and `spotify_playlists.txt`
- Add example
- Update documents

### CODE REVIEW

**Comment by sigma67** [comment]
Looks like some useful changes at first glance, although a bit difficult to compare since so many things were changed.

Is it backwards compatible with existing setups?

**Comment by PattoMotto** [comment]
@sigma67 
I upgraded the Setup script.

Before
`python Setup.py musicmanager`
After
`python Setup.py --musicmanager` OR `python Setup.py -mm`

Before
`python Setup.py mobileclient`
After
`python Setup.py --mobileclient` OR `python Setup.py -mc`

Before
`python Setup.py youtube`
After
`python Setup.py --youtube` OR `python Setup.py -yt`


And the new `headers_raw`
`python Setup.py --youtube --headers_raw "HEADERS"`


Please let me know if you've any concern with this upgrade.

**Comment by sigma67** [comment]
Yes, but that's not all you changed. There's also many changes to YouTube.py. You also didn't answer my question about backwards compatibility.

**Comment by PattoMotto** [comment]
> There's also many changes to YouTube.py. You also didn't answer my question about backwards compatibility.

YouTube.py will be 100% backward compatible.
I just moved `YTMusicTransfer` to another file and modify the main method argument getter.
Which still work when you call `YouTube.py` directly.

**Comment by lucasrangit** [comment]
@PattoMotto , @sigma67 I can try and tease out some of these changes into smaller commits if either of you don't have time. I see some useful changes and improvements.

**Comment by sigma67** [comment]
For sure, the main thing that prevented me from looking at it was the size of the change and I wasn't sure if it was compatible with my own app branch

**Comment by PattoMotto** [comment]
@lucasrangit Thanks :)

**Pull request closed without merging**
